### ISSUE TITLE
Désactiver le SSO de staging

### ISSUE THREAD

**Issue by tut-tuuut** [numerique-gouv/sso-operateur#26]
- [ ] Vérifier qu'aucun service n'utilise les SSO de prod et staging
- [ ] Passer par MCP si besoin, sinon attendre Agent Connect
- [ ] Scale à zéro les applis Scalingo
- [ ] Faire le nécessaire pour les supprimer ?

**Comment by mjeammet** [comment]
Côté staging : 
- Outline-operateur-staging n'utilise plus le sso ✅ 
- le pad-dinum par contre si ! 🟥  @tut-tuuut si tu veux le débrancher
- pas de staging pour Nextcloud donc c'est ✅

**Comment by tut-tuuut** [comment]
Staging pad : OK

**Comment by tut-tuuut** [comment]
- [ ] OK pour débrancher le staging @mjeammet 

- [ ] Regarder qui utilise le nextcloud de prod
- [ ] Faire un point nextcloud prod avec AL et Alexis
